version: "3.8"
services:
  db:
    container_name: db
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Succ355
      MYSQL_DATABASE: crud_catalogo

  server:
    container_name: server
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
  # version: "3"
  # services:
  #     www:
  #         container_name: www
  #         build: .
  #         restart: always
  #         ports: 
  #             - "80:80"
  #             - "443:443"
  #         volumes:
  #             - ./public_html/:/var/www/html
  #             - ./php.ini:/usr/local/etc/php/conf.d/30-custom.ini
  #         links:
  #             - db
  #         networks:
  #             - default
  #     db:
  #       container_name: db
  #       image: mysql:5.7
  #       restart: always
  #       environment:
  #           MYSQL_ROOT_PASSWORD: a1234
  #           MYSQL_DATABASE: test
  #           MYSQL_USER: test
  #           MYSQL_PASSWORD: a1234
  #       ports:
  #           - "3306:3306"
  #       volumes:
  #           - ./dump:/docker-entrypoint-initdb.d
  #           - persistent:/var/lib/mysql
  #       networks:
  #           - default
  #     phpmyadmin:
  #         container_name: phpmyadmin
  #         image: phpmyadmin/phpmyadmin
  #         restart: always
  #         links: 
  #             - db:db
  #         ports:
  #             - 8080:80
  #         environment:
  #             MYSQL_USER: user
  #             MYSQL_PASSWORD: test
  #             MYSQL_ROOT_PASSWORD: test
  # volumes:
  #     persistent:
  # ser_dbeaver:
  #   container_name: dbeaver
  #   image: dbeaver/cloudbeaver:latest
  #   ports:
  #     - "8200:8978"
  #   depends_on:
  #     - basedatos
  # volumes:
  #   data:

