DROP DATABASE IF EXISTS crud_catalogo;

CREATE DATABASE crud_catalogo CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

USE crud_catalogo;

CREATE TABLE t_usuarios (
    id_user INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(200) NOT NULL,
    password VARCHAR(200),
    fecha_alta DATETIME,
    ESTADO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE = innoDB;

CREATE TABLE productos (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    PRECIO FLOAT(6, 2),
    IMAGEN VARCHAR(200),
    FECHA_ALTA DATETIME,
    ESTADO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE = innoDB;

CREATE TABLE categorias (
    ID TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA VARCHAR(200) NOT NULL UNIQUE
) ENGINE = innoDB;

CREATE TABLE categorizacion (
    FKPRODUCTO INT UNSIGNED NOT NULL,
    FKCATEGORIA TINYINT(3) UNSIGNED NOT NULL,
    PRIMARY KEY (FKPRODUCTO, FKCATEGORIA),
    CONSTRAINT CATEGORIZACION_PRODUCTO FOREIGN KEY (FKPRODUCTO) REFERENCES productos (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CATEGORIZACION_CATEGORIA FOREIGN KEY (FKCATEGORIA) REFERENCES categorias (ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = innoDB;

INSERT INTO
    categorias (CATEGORIA)
VALUES ('pizzas'),
    ('bebidas'),
    ('postres'),
    ('pastas'),
    ('cafetería');

INSERT INTO
    productos (NOMBRE, PRECIO, FECHA_ALTA)
VALUES (
        'pizza de muzzarella',
        3500,
        NOW()
    ),
    ('pizza de ananá', 5700, NOW()),
    ('lasagna', 8700, NOW()),
    ('ravioli', 3800, NOW()),
    ('bebida cola', 800, NOW());

INSERT INTO categorizacion VALUES (1, 1), (2, 1), (3, 2);